### PR TITLE
Port to SDL2

### PR DESCRIPTION
**Pull request by drfiemost**
I did the port a while ago for GT2, so here's the code in case there's interest.
Not fully tested yet, I've simply applied the same changes.

### CODE REVIEW

**Comment by jpage8580** [comment]
Thanks for this. I've used your changes, and had to make a few others:

1) No audio output! (had to explicitly add the following at the start of main()

#ifdef __WIN32__
	SDL_setenv("SDL_AUDIODRIVER", "directsound", 1);
#endif

2) Key repeat - I changed the event callback to check for event.key.repeat 

3) gconsole.c - Initially there was no display

I added a gfx_flip(); where there used to be the SDL_UpdateRect() call.

Will commit a new version soon

**Comment by mrdudz** [comment]
```
#ifdef WIN32
```
shouldnt it be _WIN32

**Comment by jpage8580** [comment]
It got lost in the formatting here .. There's 2 underscores on each side. :)

**Comment by mrdudz** [comment]
> It got lost in the formatting here .. There's 2 underscores on each side. :)

but that is equally wrong - the symbol to check for windows api is _WIN32 :)

**Comment by jpage8580** [comment]
really? I read that it can be either... and considering that I'm building
on windows and it works...

**Pull request closed without merging**
